title = "Developer Log"

baseURL   = "https://cmpadden.github.io/"
copyright = "© 2020 Colton Padden"

enableEmoji            = true
enableRobotsTXT        = true

[markup]
  [markup.highlight]
    lineNos = true
    style = "monokailight"
