title = "Developer Log"

baseURL   = "https://cmpadden.github.io/blog/"
copyright = "© 2020 Colton Padden"

defaultContentLanguage = "en"
languageCode           = "en"

enableEmoji            = true
enableRobotsTXT        = true

[markup]
  [markup.highlight]
    lineNos = true
    style = "monokailight"
